apiVersion: v1
kind: Service
metadata:
  name: predictive-analysis-engine
  labels:
    app: predictive-analysis-engine
    component: simulation
spec:
  type: ClusterIP
  selector:
    app: predictive-analysis-engine
  ports:
    - name: http
      port: 7000
      targetPort: http
      protocol: TCP
